# Generated by Django 6.0.5 on 2026-05-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='rawrecord',
            name='source',
        ),
        migrations.RenameField(
            model_name='rawrecord',
            old_name='ingested_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='raw_unit',
        ),
        migrations.RemoveField(
            model_name='rawrecord',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.organization'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.rawrecord'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='scope',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
